function otrace = lowpass_equiripple(itrace, TraceNum)
%LOWPASS_EQUIRIPPLE Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.12 and the Signal Processing Toolbox 6.15.
%
% Generated on: 31-Jan-2012 19:52:48
%

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in MHz.
Fs = 250;  % Sampling Frequency

Fpass = 25;          % Passband Frequency
Fstop = 50;         % Stopband Frequency
Dpass = 0.014375281946;  % Passband Ripple
Dstop = 2.5e-005;        % Stopband Attenuation
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});

for i=1:TraceNum
    otrace(:,i)=filter(b,1, itrace(:,i));
end



% [EOF]
